# Generated by Django 5.1.5 on 2025-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_song_audio_link_alter_song_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(max_length=250, upload_to=" "),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(max_length=250, upload_to=" "),
        ),
    ]
